name: "Buildx Scripts Image"
on:
  push:
    branches:
      - build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Scripts Image
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: evinedeng/tnanko_scripts
          dockerFile: docker/Dockerfile
          platform: linux/386,linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6
          tag: latest,3,3.9,3.9.1
          dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}