# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: x_login

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4 requests html5lib
    - name: 执行x_login.py
      run: |
        python x_login.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} ${{ secrets.HOST }}
